# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iAZfd-qofMtB6pBm87RLU5iIckm6TBXt
"""

!git clone https://github.com/mariapazmachiavello/Proyecto3.git

import pandas as pd
import matplotlib.pyplot as plt

mexico = pd.read_csv("/content/Proyecto3/MEXICO_DESEMPLEO.csv",delimiter=",",encoding="latin1")
uruguay = pd.read_csv("/content/Proyecto3/URUGUAY_DESEMPLEO.csv",encoding="latin1")

mexico.columns = ["Anio","Tasa"]

mexico = mexico[mexico["Anio"].str.isnumeric()]
mexico["Anio"]=mexico["Anio"].astype(int)
mexico["Anio"].replace({"09/2023":"2023"})

#mexico["Tasa"]= mexico["Tasa"].str.replace('"','')
mexico["Tasa"]=mexico["Tasa"].astype(float)

mexico_filtrado = mexico[(mexico["Anio"]<=2017)]

plt.plot(uruguay["año"],uruguay["valor"],label="uruguay")
plt.plot(mexico_filtrado["Anio"],mexico_filtrado["Tasa"],label="mexico")